name: Vite Three.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm npm ci
        npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:owner/repo.git
        BRANCH: gh-pages
        FOLDER: dist
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
